name: "Bug report"
description: "File a bug"
labels: ["type/bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: blueprint
    attributes:
      label: Blueprint used
      description: Path or description of the blueprint
  - type: dropdown
    id: version
    attributes:
      label: Python version
      options:
        - "3.10"
        - "3.11"
        - "Other"
  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: shell
